@Api_HostAddress = http://localhost:5017

GET {{Api_HostAddress}}/
Accept: application/json

###

GET {{Api_HostAddress}}/HealthCheck
Accept: application/json

###

GET {{Api_HostAddress}}/Notes
Accept: application/json

###

POST {{Api_HostAddress}}/Notes
Content-Type: application/json

{
	"title": "First note",
	"content": "Database-backed API is ready."
}

###

GET {{Api_HostAddress}}/Notes/1
Accept: application/json

###

PUT {{Api_HostAddress}}/Notes/1
Content-Type: application/json

{
	"title": "Updated note",
	"content": "Updated from Api.http"
}

###

DELETE {{Api_HostAddress}}/Notes/1
Accept: application/json

###

GET {{Api_HostAddress}}/Projects
Accept: application/json

###

POST {{Api_HostAddress}}/Projects
Content-Type: application/json

{
	"name": "Woodland Fox",
	"wood": "Basswood",
	"status": "In Progress",
	"description": "Practice carving with simple fur planes."
}

###

GET {{Api_HostAddress}}/Projects/1
Accept: application/json

###

PUT {{Api_HostAddress}}/Projects/1
Content-Type: application/json

{
	"name": "Updated Woodland Fox",
	"wood": "Basswood",
	"status": "Complete",
	"description": "Finished from Api.http"
}

###

DELETE {{Api_HostAddress}}/Projects/1
Accept: application/json

###
